from enum import Enum

class Button(Enum):
    BUTTON_REC = 2.30
    BUTTON_MODE = 1.98
    BUTTON_PLAY = 1.65
    BUTTON_SET = 1.11
    BUTTON_VOL_MINUS = 0.82
    BUTTON_VOL_PLUS = 0.38

class AnimationType(Enum):
    PROCESSING = 1
    SUCCESS = 2
    WAITING = 3
    STARTUP = 4
    SHUTDOWN = 5
    RAINBOW_PULSE = 6
    FIREWORK = 7
    POLICE = 8
    HEARTBEAT = 9
    FIRE = 10
    CANDY_CANE = 11
    STROBE = 12
    HEARTBEAT_FLASH = 13
    DEVICE_SHUTDOWN = 14
    BLINKING_WARNING = 15
    WAKE_WORD = 16
    SPEECH_PROCESSING = 17
    NOTIFICATION_HIGHLIGHT = 18
    ERROR_BLINK = 19
    PAIRING = 20
    VOICE_RESPONSE = 21
    ACTION_CONFIRMATION = 22
    CONFIGURABLE_PULSE = 23
    CONFIGURABLE_CHASE = 24
    CONFIGURABLE_SPARKLE = 25
    CONFIGURABLE_GRADIENT = 26
    CONFIGURABLE_WAVE = 27
    STATUS_INDICATOR = 28
    PROGRESS_INDICATOR = 29
    CONFIGURABLE_FIREWORK = 30
    CONFIGURABLE_METEOR = 31
    CONFIGURABLE_RIPPLE = 32
    CONFIGURABLE_PIXELS = 33
    CONFIGURABLE_SCANNER = 34
    CONFIGURABLE_STROBE_PATTERNS = 35
    CONFIGURABLE_AURORA = 36
    CONFIGURABLE_PLASMA = 37

class Pattern(Enum):
    SOLID = "SOLID"
    GRADIENT = "GRADIENT"
    RAINBOW = "RAINBOW"
    SPARKLE = "SPARKLE"

class Speed(Enum):
    VERY_SLOW = "VERY_SLOW"
    SLOW = "SLOW"
    MEDIUM = "MEDIUM"
    FAST = "FAST"
    VERY_FAST = "VERY_FAST"

class Direction(Enum):
    FORWARD = "FORWARD"
    BACKWARD = "BACKWARD"
    BOUNCE = "BOUNCE"
    RANDOM = "RANDOM"

class PredefinedColor(Enum):
    # Basic Colors
    RED = "RED"
    GREEN = "GREEN"
    BLUE = "BLUE"
    WHITE = "WHITE"
    BLACK = "BLACK"
    YELLOW = "YELLOW"
    PURPLE = "PURPLE"
    ORANGE = "ORANGE"

    # Reds & Pinks
    CRIMSON = "CRIMSON"
    DARKRED = "DARKRED"
    MAROON = "MAROON"
    PINK = "PINK"
    DEEPPINK = "DEEPPINK"
    HOTPINK = "HOTPINK"
    SALMON = "SALMON"
    CORAL = "CORAL"

    # Oranges & Browns
    DARKORANGE = "DARKORANGE"
    GOLDENROD = "GOLDENROD"
    GOLD = "GOLD"
    CHOCOLATE = "CHOCOLATE"
    BROWN = "BROWN"
    SIENNA = "SIENNA"
    SANDYBROWN = "SANDYBROWN"
    PEACHPUFF = "PEACHPUFF"

    # Yellows
    LIGHTYELLOW = "LIGHTYELLOW"
    KHAKI = "KHAKI"
    DARKKHAKI = "DARKKHAKI"
    OLIVE = "OLIVE"

    # Greens
    LIME = "LIME"
    LIMEGREEN = "LIMEGREEN"
    FORESTGREEN = "FORESTGREEN"
    SEAGREEN = "SEAGREEN"
    SPRINGGREEN = "SPRINGGREEN"
    DARKGREEN = "DARKGREEN"
    MEDIUMSEAGREEN = "MEDIUMSEAGREEN"
    PALEGREEN = "PALEGREEN"

    # Blues & Cyans
    CYAN = "CYAN"
    DARKCYAN = "DARKCYAN"
    LIGHTBLUE = "LIGHTBLUE"
    DEEPSKYBLUE = "DEEPSKYBLUE"
    NAVY = "NAVY"
    ROYALBLUE = "ROYALBLUE"
    MEDIUMBLUE = "MEDIUMBLUE"
    AQUAMARINE = "AQUAMARINE"

    # Purples & Violets
    MAGENTA = "MAGENTA"
    DARKMAGENTA = "DARKMAGENTA"
    VIOLET = "VIOLET"
    PLUM = "PLUM"
    DARKVIOLET = "DARKVIOLET"
    INDIGO = "INDIGO"
    MEDIUMORCHID = "MEDIUMORCHID"
    BLUEVIOLET = "BLUEVIOLET"

    # Whites & Grays
    SNOW = "SNOW"
    GHOSTWHITE = "GHOSTWHITE"
    WHITESMOKE = "WHITESMOKE"
    SILVER = "SILVER"
    GRAY = "GRAY"
    DARKGRAY = "DARKGRAY"
    DIMGRAY = "DIMGRAY"
    GAINSBORO = "GAINSBORO"
